# Write your MySQL query statement below
SELECT D.NAME AS DEPARTMENT, E.NAME AS EMPLOYEE, E.SALARY
FROM EMPLOYEE E
JOIN DEPARTMENT D 
ON E.DEPARTMENTID = D.ID 
WHERE E.SALARY = (
    SELECT MAX(E1.SALARY)
    FROM EMPLOYEE E1
    WHERE E1.DEPARTMENTID = E.DEPARTMENTID
);